- name: apt_update
  ansible.builtin.apt: update_cache=yes

- name: dnf_update
  ansible.builtin.dnf: update_cache=yes

- name: reboot
  ansible.builtin.reboot:
    msg: "Reboot initiated by Ansible handler"
    pre_reboot_delay: 0
    post_reboot_delay: 30
    reboot_timeout: 600
