- name: Install Joplin (Debian and Fedora)
  ansible.builtin.shell: wget -O - https://raw.githubusercontent.com/laurent22/joplin/dev/Joplin_install_and_update.sh | bash
  become_user: '{{ target_user }}'
