- name: Update community.general collection
  ansible.builtin.command:
    cmd: ansible-galaxy collection install community.general --upgrade
  become: true
  become_user: '{{ target_user }}'
  run_once: true

